# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/adv/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 33250932124e0cf4e2987bb1345b35768d571ff6

{
  "title": "Стул IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/10/
Content-Type: application/json
Authorization: Token 33250932124e0cf4e2987bb1345b35768d571ff6

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator['id']=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2020-10-01
Content-Type: application/json

###

# удаление
DELETE  {{baseUrl}}/adv/9/
Authorization: Token 33250932124e0cf4e2987bb1345b35768d571ff6
